spring:
  datasource:
    url: jdbc:postgresql://test-db.chs4wq8g04j6.us-west-1.rds.amazonaws.com/postgres
    username: postgres
    password: testpassword
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PosgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: false # changed this so manual logging is more readable
    hibernate:
      ddl-auto: update # update for final, create-drop for testing
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
server:
  port: 8080
  error:
    path: /user/error
    whitelabel:
      enabled: false

# TODO: bad idea to commit access keys to version control, but we gotta cut some corners lol
# TODO: just remember to revoke and refresh this once we find a better solution. We just need this for testing rn.
aws:
  access:
    key:
      id: AKIAQXPZC3TY6AR4FWMJ
  secret:
    access:
      key: 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
  s3:
    region: us-west-1
    bucket: visionbucket